version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_API_TOKEN=${BOT_API_TOKEN}
      - NASA_API_KEY=${NASA_API_KEY}
    ports:
      - "80:80"
    restart: always
